// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CallToAction: typeof import('./src/components/callToAction.vue')['default']
    FeatureSection: typeof import('./src/components/featureSection.vue')['default']
    HeadSection: typeof import('./src/components/headSection.vue')['default']
    MyTable: typeof import('./src/components/myTable.vue')['default']
    MyTeam: typeof import('./src/components/myTeam.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
